server:
  port: 8201
spring:
  application:
    name: service-hosp
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yygh_cmn?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mapper xml文件路径
#mybatis-plus:
#  mapper-locations: classpath:com/rbing/mapper/xml/*.xml